-- Alert rules (rule-based anomaly detection)
CREATE TABLE IF NOT EXISTS alert_rule (
    id              BIGINT PRIMARY KEY,
    tenant_id       VARCHAR(32) NOT NULL,
    name            TEXT NOT NULL,
    description     TEXT,
    rule_type       VARCHAR(32) NOT NULL,         -- frequency, consecutive, composite
    config          JSONB NOT NULL,               -- rule parameters
    -- config example for frequency: {"event_type": "leave_submit", "window_days": 30, "threshold": 5}
    -- config example for consecutive: {"event_type": "checkin_absent", "consecutive_count": 3}
    severity        VARCHAR(16) NOT NULL DEFAULT 'medium',  -- low / medium / high / critical
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_by      BIGINT,
    updated_by      BIGINT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);

CREATE INDEX idx_alert_rule_tenant ON alert_rule(tenant_id);

-- Student alerts (generated by rule engine)
CREATE TABLE IF NOT EXISTS student_alert (
    id              BIGINT PRIMARY KEY,
    tenant_id       VARCHAR(32) NOT NULL,
    student_id      BIGINT NOT NULL,
    alert_rule_id   BIGINT NOT NULL REFERENCES alert_rule(id),
    rule_name       TEXT NOT NULL,
    severity        VARCHAR(16) NOT NULL,
    trigger_data    JSONB NOT NULL,               -- snapshot of data that triggered the alert
    status          VARCHAR(16) NOT NULL DEFAULT 'open',  -- open / acknowledged / resolved / dismissed
    acknowledged_by BIGINT,
    acknowledged_at TIMESTAMPTZ,
    resolved_at     TIMESTAMPTZ,
    note            TEXT,                          -- counselor notes
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_alert_student ON student_alert(tenant_id, student_id);
CREATE INDEX idx_alert_status ON student_alert(status) WHERE status = 'open';
CREATE INDEX idx_alert_rule ON student_alert(alert_rule_id);

COMMENT ON TABLE alert_rule IS '异常预警规则';
COMMENT ON TABLE student_alert IS '学生异常预警记录';
