global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'xg-java'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['xg-java:8080']

  - job_name: 'xg-python'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['xg-python:8000']
