package com.xg.business.workstudy.service;

import com.xg.common.exception.ErrorCode;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum WorkStudyErrorCode implements ErrorCode {

    POSITION_NOT_FOUND("POSITION_NOT_FOUND", "勤工助学岗位不存在"),
    POSITION_CLOSED("POSITION_CLOSED", "岗位已关闭或不在招募中"),
    POSITION_FULL("POSITION_FULL", "岗位已招满"),
    POSITION_NOT_ACCEPTING("POSITION_NOT_ACCEPTING", "该岗位暂停招新"),
    STUDENT_FIXED_LIMIT_REACHED("STUDENT_FIXED_LIMIT_REACHED", "本学年固定岗在岗数已达上限"),
    STUDENT_TEMP_LIMIT_REACHED("STUDENT_TEMP_LIMIT_REACHED", "本学年临时岗在岗数已达上限"),
    POSITION_INELIGIBLE("POSITION_INELIGIBLE", "不符合岗位申请条件"),
    POSITION_AID_ONLY("POSITION_AID_ONLY", "该岗位仅面向家庭经济困难学生开放申请"),
    APPLICATION_NOT_FOUND("APPLICATION_NOT_FOUND", "申请不存在"),
    APPLICATION_ALREADY_EXISTS("APPLICATION_ALREADY_EXISTS", "已申请过该岗位"),
    APPLICATION_ALREADY_DECIDED("APPLICATION_ALREADY_DECIDED", "申请已处理，不可重复决定"),
    INTERVIEW_INVALID_STATE("INTERVIEW_INVALID_STATE", "仅待处理申请可发面试通知"),
    INTERVIEW_BODY_REQUIRED("INTERVIEW_BODY_REQUIRED", "通知正文不能为空"),
    INVALID_DECISION_STATUS("INVALID_DECISION_STATUS", "决定状态非法"),
    APPLICATION_NOT_HIRED("APPLICATION_NOT_HIRED", "岗位申请尚未录用，无法上报工时"),
    APPLICATION_NOT_ON_DUTY("APPLICATION_NOT_ON_DUTY", "该申请不在在岗状态，无法离岗"),
    OFFBOARD_FORBIDDEN("OFFBOARD_FORBIDDEN", "无权对该申请执行离岗操作"),
    TIMESHEET_NOT_FOUND("TIMESHEET_NOT_FOUND", "工时记录不存在"),
    TIMESHEET_ALREADY_REPORTED("TIMESHEET_ALREADY_REPORTED", "该月工时已上报"),
    TIMESHEET_NOT_PENDING_CONFIRM("TIMESHEET_NOT_PENDING_CONFIRM", "当前工时状态不允许学生确认"),
    TIMESHEET_NOT_DISPUTED("TIMESHEET_NOT_DISPUTED", "工时未处于异议状态，无法裁定"),
    TIMESHEET_NO_PENDING_TASK("TIMESHEET_NO_PENDING_TASK", "工时工作流无待办任务"),
    WORKFLOW_NO_PENDING_TASK("WORKFLOW_NO_PENDING_TASK", "工作流无待办任务"),
    SALARY_NOT_FOUND("SALARY_NOT_FOUND", "薪资记录不存在"),
    SALARY_NOT_PENDING("SALARY_NOT_PENDING", "薪资记录已处理或不在审批中"),
    SALARY_INVALID_POSITION_RATE("SALARY_INVALID_POSITION_RATE", "岗位未配置薪资单位或单价，无法申报"),
    APPLICATION_NOT_HIRED_FOR_SALARY("APPLICATION_NOT_HIRED_FOR_SALARY", "学生未在该岗位录用，不能申报薪资"),
    SALARY_CAP_EXCEEDED("SALARY_CAP_EXCEEDED", "本月该用工单位累计申报金额已超过设定上限"),
    OUT_OF_POSITION_WINDOW("OUT_OF_POSITION_WINDOW", "当前不在岗位设定时段,无法创建/修改岗位"),
    OUT_OF_APPLICATION_WINDOW("OUT_OF_APPLICATION_WINDOW", "当前不在学生上岗申请时段,无法提交申请"),
    OUT_OF_SALARY_WINDOW("OUT_OF_SALARY_WINDOW", "当前不在薪酬申报时段,无法提交薪酬"),
    ASSIGNEE_BIZTYPE_MISMATCH("ASSIGNEE_BIZTYPE_MISMATCH", "工作流节点受理人策略与流程 bizType 不匹配");

    private final String code;
    private final String message;
}
