#!/usr/bin/env bash
# Refreshes the version-snapshot block inside docs/release.md.
# Replaces everything between <!-- VERSION-SNAPSHOT-START --> and <!-- ...END -->
# so the file never lies about current versions.
#
# Run before tagging a release, and after any:
#   - new tenant migration (Vxxx)
#   - bump in any package.json / pyproject / gradle wrapper
#   - bump in xg-backend version

set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
TARGET="$ROOT/docs/release.md"

# ─── collect versions ────────────────────────────────────────────────

# Java (xg-backend root build.gradle: `version = '...'` lives inside allprojects {})
java_ver=$(awk -F"'" '/version[[:space:]]*=/{print $2; exit}' "$ROOT/xg-backend/build.gradle" 2>/dev/null || true)
[ -z "$java_ver" ] && java_ver="(not set)"

# AI sidecar (xg-ai/pyproject.toml)
ai_ver=$(awk -F'"' '/^version[[:space:]]*=/{print $2; exit}' "$ROOT/xg-ai/pyproject.toml")

# Web + Mini package.json
web_ver=$(python3 -c "import json;print(json.load(open('$ROOT/xg-frontend/apps/web/package.json'))['version'])")
mini_ver=$(python3 -c "import json;print(json.load(open('$ROOT/xg-frontend/apps/mini/package.json'))['version'])")

# Latest tenant migration (sort -V for natural numeric order on Vxx_)
mig_dir="$ROOT/xg-backend/xg-app/src/main/resources/db/migration/tenant"
latest_migration=$(ls -1 "$mig_dir" | grep -E '^V[0-9]+__' | sort -V | tail -1)
[ -z "$latest_migration" ] && latest_migration="(none)"

# Gradle wrapper
gradle_ver=$(awk -F'gradle-' '/distributionUrl/{split($2,a,"-"); print a[1]; exit}' \
  "$ROOT/xg-backend/gradle/wrapper/gradle-wrapper.properties")

# ─── build replacement block ─────────────────────────────────────────

read -r -d '' BLOCK <<EOF || true
<!-- VERSION-SNAPSHOT-START — auto-generated by scripts/sync-release-snapshot.sh, do not hand-edit -->
当前最高版本快照（\`bash scripts/sync-release-snapshot.sh\` 刷新）：
- Java (\`xg-backend\`): \`$java_ver\`
- AI sidecar (\`xg-ai/pyproject.toml\`): \`$ai_ver\`
- Web (\`xg-frontend/apps/web\`): \`$web_ver\`
- Mini (\`xg-frontend/apps/mini\`): \`$mini_ver\`
- Latest tenant migration: \`$latest_migration\`
- Gradle wrapper: \`$gradle_ver\`
<!-- VERSION-SNAPSHOT-END -->
EOF

# ─── splice into target ──────────────────────────────────────────────

# Use python to do precise marker-bounded replacement (sed/awk are awkward for
# multi-line replace).
python3 - "$TARGET" <<PY
import re, sys, pathlib
target = pathlib.Path(sys.argv[1])
src = target.read_text(encoding="utf-8")
new_block = """$BLOCK"""
pattern = re.compile(
    r"<!-- VERSION-SNAPSHOT-START.*?<!-- VERSION-SNAPSHOT-END -->",
    re.DOTALL,
)
if not pattern.search(src):
    sys.exit("error: VERSION-SNAPSHOT markers not found in " + str(target))
out = pattern.sub(new_block.strip(), src)
target.write_text(out, encoding="utf-8")
print("updated", target)
PY

echo "Snapshot refreshed:"
echo "  Java     : $java_ver"
echo "  AI       : $ai_ver"
echo "  Web      : $web_ver"
echo "  Mini     : $mini_ver"
echo "  Migration: $latest_migration"
echo "  Gradle   : $gradle_ver"
